project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-GMY5LHEEJL"
  # title: "My Website"
  # title-prefix: "Site Name"
  title: "Brian Brost"
  # title-prefix: "Brian Brost"
  favicon: media/logo.png
  navbar:
    logo: media/logo.png
    # logo-alt:
    right:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - href: showcase/index.qmd
        text: Showcase
      # - href: publications/index_old.qmd
      - href: publications/index.qmd
        text: Publications 
  # page-footer:
    # background: light # or `dark` or omit this option altogether (footer color will match page body color)
    # left: Brian M. Brost &copy; 2025
    # right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/bmbrost/bmbrost.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      - cosmo
      - styles.scss
    # mainfont: Petrona
    # css: styles.css
    toc: true
    # page-layout: full


