---
# title: "Publications"
pagetitle: "Brian Brost - Publications"  # this goes in the browser tab
toc: false

format: 
  html:
    grid:
      sidebar-width: 350px
      body-width: 600px
      margin-width: 350px
      gutter-width: 2rem
---

<!-- Examples for inspiration: -->
<!-- https://affcom.ku.edu/publications.html; https://github.com/jmgirard/affcomlab/tree/main -->
<!-- https://faculty.washington.edu/masiello/publications/ -->
<!-- https://silviacanelon.com/publication/#category=research -->

<div style="text-align:justify">

<!-- reversed ordered list -->
<ol reversed>

#### Manuscripts in prep and review
<hr>

<li> Sterling, J.T., and B.M. Brost. Summer resource limitation as a likely mechanism impacting northern fur seal (*Callorhinus ursinus*) recovery. </li>

<li> Brost, B.M, and N. Young. Hierarchical models improve inference concerning marine mammal mortalities incidental to commercial fishing activities. </li>

<li> Zeppelin, T.K., B.M. Brost, D.S. Johnson, C.M. Kurle, B.A. Güell, C. Keller, M.T. Williams, and A.E. York. Determining cryptic life history milestones using isotopic markers in northern fur seal (*Callorhinus ursinus*) vibrissae. </li>

<li> McCormley, M., B.M. Brost, B. Fadely, and A. Warlick. A hierarchical multistate model reveals parturition and pupping patterns for western Steller sea lions (*Eumetopias jubatus*). </li>

<li> Brost, B.M. A general framework for quantifying telemetry measurement error without a secondary data source. </li>

<li> Brost, B.M. Abundance estimation of an endangered population of beluga whales using a dynamic N-mixture model. </li>

#### Peer-reviewed publications
<hr>

<li> Conn, P.B., J.M. Ver Hoef, B.T. McClintock, D.S. Johnson, and B. Brost. 2022. A GLMM approach for combining multiple relative abundance surfaces. *Methods in Ecology and Evolution* **13**:2236–2247. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Conn_et_al_MEE_2022.pdf){target="_blank"} </li>

<li> Johnson, D.S., B.M. Brost, and M.B. Hooten. 2022. Greater than the sum of its parts: computationally flexible Bayesian hierarchical modeling. *Journal of Agricultural, Biological, and Environmental Statistics* **27**:382–400. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Johnson_et_al_JABES_2022.pdf){target="_blank"} </li>

<li> Hooten, M.B., D.S. Johnson, and B.M. Brost. 2021. Making recursive Bayesian inference accessible. *The American Statistician* **75**:185–194. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Hooten_et_al_AmStat_2021.pdf){target="_blank"} </li>

<li> Brost, B.M., M.B. Hooten, and R.J. Small. 2020. Model-based clustering reveals patterns in central place use of a marine top predator. *Ecosphere* **11**(6):e03123. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_et_al_Ecosphere_2020.pdf){target="_blank"} </li>

<li> Fritz, L., B. Brost, E. Laman, K. Luxa, K. Sweeney, J. Thomason, D. Tollit, W. Walker, and T. Zeppelin. 2019. A re-examination of the relationship between Steller sea lion (*Eumetopias jubatus*) diet and population trend using data from the Aleutian Islands. *Canadian Journal of Zoology* **97**:1137–1155. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Fritz_et_al_CJZ_2019.pdf){target="_blank"} </li>

<li> Zeppelin, T., N. Pelland, J. Sterling, B. Brost, S. Melin, D. Johnson, M. Lea, and R. Ream. 2019. Migratory strategies of juvenile northern fur seals (*Callorhinus ursinus*): bridging the gap between pups and adults. *Scientific Reports* **9**:13921. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Zeppelin_et_al_SciReports_2019.pdf){target="_blank"} </li>

<li> Brost, B.M., B.A. Mosher, and K.A. Davenport. 2018. A model-based solution for observational errors in laboratory studies. *Molecular Ecology Resources* **18**:580–589. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_et_al_MER_2018.pdf){target="_blank"} </li>

<li> Davenport, K.A., B.A. Mosher, B.M. Brost, D.M. Henderson, N.A. Denkers, A.V. Nalls, E. McNulty, C.K. Mathiason, and E.A. Hoover. 2018. Assessment of chronic wasting disease prion shedding in deer saliva with occupancy modeling. *Journal of Clinical Microbiology* **56**:e01243–17. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Davenport_et_al_JCM_2018.pdf){target="_blank"} </li>

<li> Brost, B.M., M.B. Hooten, and R.J. Small. 2017. Leveraging constraints and biotelemetry data to pinpoint repetitively used spatial features. *Ecology* **98**:12–20. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_et_al_Ecology_2017.pdf){target="_blank"} </li>

<li> Hefley, T.J., K.M. Broms, B.M. Brost, F.E. Buderman, S.L. Kay, H.R. Scharf, J.R. Tipton, P.J. Williams, and M.B. Hooten. 2017. The basis function approach for modeling autocorrelation in ecological data. *Ecology* **98**:632–646. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Hefley_et_al_Ecology_2017.pdf){target="_blank"} </li>

<li> Hefley, T.J., B.M. Brost, and M.B. Hooten. 2017. Bias correction of bounded location errors in presence-only data. *Methods in Ecology and Evolution* **8**:1566–1573. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Hefley_et_al_MEE_2017.pdf){target="_blank"} </li>

<li> Small, R.J., B. Brost, M. Hooten, M. Castellote, and J. Mondragon. 2017. Potential for spatial displacement of Cook Inlet beluga whales by anthropogenic noise in critical habitat. *Endangered Species Research* **32**:43–57. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Small_et_al_ESR_2017.pdf){target="_blank"} </li>

<li> Hooten, M.B., F.E. Buderman, B.M. Brost, E.M. Hanks, and J.S. Ivan. 2016. Hierarchical animal movement models for population-level inference. *Environmetrics* **27**:322–333. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Hooten_et_al_Environmetrics_2016.pdf){target="_blank"} </li>

<li> Brost, B.M., M.B. Hooten, E.M. Hanks, and R.J. Small. 2015. Animal movement constraints improve resource selection inference in the presence of telemetry error. *Ecology* **96**:2590–2597. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_et_al_Ecology_2015.pdf){target="_blank"} </li>

<li> Brost, B.M., and P. Beier. 2012. Comparing linkage designs based on land facets to linkage designs based on focal species. *PLoS One* **7**:e48965. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_Beier_PONE_2012.pdf) </li>

<li> Brost, B.M., and P. Beier. 2012. Use of land facets to design linkages for climate change. *Ecological Applications* **22**:87–103. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Brost_Beier_EcolApps_2012.pdf){target="_blank"} </li>

<li> Beier, P., and B. Brost. 2010. Use of land facets to plan for climate change: Conserving the arenas, not the actors. *Conservation Biology* **24**:701–710. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Beier_Brost_ConsBio_2010.pdf){target="_blank"} </li>

#### Book chapters and white papers
<hr>

<li> McMaster, M.A., A. Thode, B. Brost, M. Williamson, E. Aumack, D. Mertz. 2010. Changes in vegetation and fuels due to the Warm Fire on the Kaibab National Forest. *Joint Fire Science Program Research Project Reports* 34. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/McMaster_et_al_JFSP_2010.pdf){target="_blank"} </li>

<li> Wydeven, A.P., A. Treves, B. Brost, and J.E. Wiedenhoeft. 2004. Characteristics of wolf packs in Wisconsin: Identification of traits influencing depredation. In *People and Predators: From Conflict to Coexistence,* eds. N. Fascione, A. Delach, and M. E. Smith. Island Press, Washington, D.C. [{{<fa regular file-pdf title="PDF">}}](https://bmbrost.github.io/publications/pdf/Wydeven_et_al_preprint_2004.pdf){target="_blank"} </li>

</ol>

</div>

<!-- Add footer -->
<!-- See: https://quarto.org/docs/authoring/article-layout.html#overflowing-content -->
::: {.column-page}
<footer class="footer-main"> 
Brian M. Brost &copy; 2025 
</footer>
:::
